[package]
name = "dict"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = "0.30"
serde = { version = "1.0", features = ["derive"] }
regex = "1.10"
scraper = "0.18"
tokio = { version = "1.0", features = ["full"] }
